config:

  data:
   proxy-supp:
    use-proxy: false
    proxy: "" # rotating proxy
   custom-branding:
     use-custom-branding: true # but have set the pfp and banner in the input/watermarking folder and also put display name below
     display-name: ".gg/loop"

# NONE OF THIS CODE IS MINE
